### ISSUE TITLE
Foreach loop bug with arrays

### ISSUE THREAD

**Issue by atlesn** [P-star/P-star#47]
Foreach loop crashes when iterator arrays or hashes of zero length. Add check for zero-length arrays.

Program received signal SIGFPE, Arithmetic exception.
do_operator_recursive (final_result=0x61c7c0, exp_state=0x61d530, this=0x61e210) at value_array.cpp:155
155			int index_mod = index % max;

#0  do_operator_recursive (final_result=0x61c7c0, exp_state=0x61d530, this=0x61e210) at value_array.cpp:155
#1  wpl_value_array::do_operator_recursive (this=0x61e210, exp_state=0x61d530, final_result=0x61c7c0) at value_array.cpp:150
#2  0x00007ffff7972107 in wpl_value_hash::do_operator (this=0x617790, exp_state=0x61d530, final_result=0x61c7c0, op=<optimized out>, lhs=<optimized out>, 
    rhs=<optimized out>) at value_hash.cpp:99
#3  0x00007ffff79691e8 in wpl_value::do_fastop (this=0x617700, exp_state=<optimized out>, final_result=<optimized out>, op=0x7ffff7bd86a0) at value.cpp:118
#4  0x00007ffff7972ce2 in wpl_value_unresolved_identifier::do_fastop (this=<optimized out>, exp_state=0x61d530, final_result=0x61c7c0, op=0x7ffff7bd86a0)
    at value_unresolved.cpp:68
#5  0x00007ffff794b975 in wpl_expression::run (this=<optimized out>, state=<optimized out>, final_result=<optimized out>) at expression.cpp:78
#6  0x00007ffff795a6e3 in wpl_block_foreach::run (this=0x6139c0, state=<optimized out>, final_result=0x7fffffffe3b0) at block_foreach.cpp:56
#7  0x00007ffff799a8eb in wpl_block_state::run_child (this=<optimized out>, child=0x6139e8, index=<optimized out>, final_result=0x7fffffffe3b0) at block_state.cpp:68
#8  0x00007ffff795326c in wpl_block::run_children (this=0x60e6f0, block_state=0x6170d0, final_result=0x7fffffffe3b0) at block.cpp:71
#9  0x00007ffff793ca6f in wpl_program::run (this=<optimized out>, io=...) at program.cpp:134
#10 0x0000000000401e00 in main (argc=3, argv=0x7fffffffec58) at main.cpp:86

**Comment by atlesn** [comment]
Still issue...
